sudo: false
language: objective-c
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode7.3
branches:
  only:
  - master
  - development
script:
- set -o pipefail && xcodebuild -workspace Example/topFloatingView.xcworkspace -scheme topFloatingView -configuration Debug -sdk iphonesimulator9.3 -destination "platform=iOS Simulator,OS=9.3,name=iPhone 6" build | xcpretty -c
